[2024-01-22T23:02:48.862+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-12-22T08:00:00+00:00 [queued]>
[2024-01-22T23:02:48.867+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-12-22T08:00:00+00:00 [queued]>
[2024-01-22T23:02:48.867+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 5
[2024-01-22T23:02:48.874+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): test> on 2022-12-22 08:00:00+00:00
[2024-01-22T23:02:48.879+0000] {standard_task_runner.py:57} INFO - Started process 422 to run task
[2024-01-22T23:02:48.883+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_sample_dag', 'test', 'scheduled__2022-12-22T08:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp8746xe3b']
[2024-01-22T23:02:48.886+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask test
[2024-01-22T23:02:48.925+0000] {task_command.py:416} INFO - Running <TaskInstance: first_sample_dag.test scheduled__2022-12-22T08:00:00+00:00 [running]> on host 3b2231e5c840
[2024-01-22T23:02:48.970+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_sample_dag' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2022-12-22T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-22T08:00:00+00:00'
[2024-01-22T23:02:48.978+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-22T23:02:48.979+0000] {spark_submit.py:366} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark:7077 --name arrow-spark /user/local/spark/app/spark.py
[2024-01-22T23:02:50.110+0000] {spark_submit.py:536} INFO - python3: can't open file '/user/local/spark/app/spark.py': [Errno 2] No such file or directory
[2024-01-22T23:02:50.117+0000] {spark_submit.py:536} INFO - 24/01/22 23:02:50 INFO ShutdownHookManager: Shutdown hook called
[2024-01-22T23:02:50.119+0000] {spark_submit.py:536} INFO - 24/01/22 23:02:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-4f9f4bf7-641b-400d-84d3-aa04fc4d3d54
[2024-01-22T23:02:50.148+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 467, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark:7077 --name arrow-spark /user/local/spark/app/spark.py. Error code is: 2.
[2024-01-22T23:02:50.151+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_sample_dag, task_id=test, execution_date=20221222T080000, start_date=20240122T230248, end_date=20240122T230250
[2024-01-22T23:02:50.159+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task test (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark:7077 --name arrow-spark /user/local/spark/app/spark.py. Error code is: 2.; 422)
[2024-01-22T23:02:50.184+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-22T23:02:50.209+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
