[2024-01-22T22:22:13.132+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-12-22T08:00:00+00:00 [queued]>
[2024-01-22T22:22:13.138+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-12-22T08:00:00+00:00 [queued]>
[2024-01-22T22:22:13.138+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2024-01-22T22:22:13.146+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): test> on 2022-12-22 08:00:00+00:00
[2024-01-22T22:22:13.156+0000] {standard_task_runner.py:57} INFO - Started process 51 to run task
[2024-01-22T22:22:13.160+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_sample_dag', 'test', 'scheduled__2022-12-22T08:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpcglfdzhh']
[2024-01-22T22:22:13.165+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask test
[2024-01-22T22:22:13.221+0000] {task_command.py:416} INFO - Running <TaskInstance: first_sample_dag.test scheduled__2022-12-22T08:00:00+00:00 [running]> on host 19955daf03c7
[2024-01-22T22:22:13.283+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_sample_dag' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2022-12-22T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-22T08:00:00+00:00'
[2024-01-22T22:22:13.291+0000] {spark_submit.py:236} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-01-22T22:22:13.292+0000] {spark_submit.py:366} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py
[2024-01-22T22:22:13.314+0000] {spark_submit.py:536} INFO - /opt/spark/bin/spark-class: line 71: /usr/lib/jvm/java-8-openjdk-amd64//bin/java: No such file or directory
[2024-01-22T22:22:13.315+0000] {spark_submit.py:536} INFO - /opt/spark/bin/spark-class: line 96: CMD: bad array subscript
[2024-01-22T22:22:13.327+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 467, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py. Error code is: 1.
[2024-01-22T22:22:13.330+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_sample_dag, task_id=test, execution_date=20221222T080000, start_date=20240122T222213, end_date=20240122T222213
[2024-01-22T22:22:13.338+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task test (Cannot execute: spark-submit --master yarn --name arrow-spark /usr/local/spark/app/spark.py. Error code is: 1.; 51)
[2024-01-22T22:22:13.374+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-22T22:22:13.389+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-22T22:41:10.061+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-12-22T08:00:00+00:00 [queued]>
[2024-01-22T22:41:10.067+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-12-22T08:00:00+00:00 [queued]>
[2024-01-22T22:41:10.067+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2024-01-22T22:41:10.076+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): test> on 2022-12-22 08:00:00+00:00
[2024-01-22T22:41:10.084+0000] {standard_task_runner.py:57} INFO - Started process 151 to run task
[2024-01-22T22:41:10.088+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_sample_dag', 'test', 'scheduled__2022-12-22T08:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp2x4tsa0_']
[2024-01-22T22:41:10.092+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask test
[2024-01-22T22:41:10.135+0000] {task_command.py:416} INFO - Running <TaskInstance: first_sample_dag.test scheduled__2022-12-22T08:00:00+00:00 [running]> on host 3441088a5e19
[2024-01-22T22:41:10.185+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_sample_dag' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2022-12-22T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-22T08:00:00+00:00'
[2024-01-22T22:41:10.193+0000] {spark_submit.py:236} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-01-22T22:41:10.194+0000] {spark_submit.py:366} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark /user/local/spark/app/spark.py
[2024-01-22T22:41:10.211+0000] {spark_submit.py:536} INFO - /opt/spark/bin/spark-class: line 71: /usr/lib/jvm/java-8-openjdk-amd64//bin/java: No such file or directory
[2024-01-22T22:41:10.212+0000] {spark_submit.py:536} INFO - /opt/spark/bin/spark-class: line 96: CMD: bad array subscript
[2024-01-22T22:41:10.225+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 467, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark /user/local/spark/app/spark.py. Error code is: 1.
[2024-01-22T22:41:10.229+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_sample_dag, task_id=test, execution_date=20221222T080000, start_date=20240122T224110, end_date=20240122T224110
[2024-01-22T22:41:10.238+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task test (Cannot execute: spark-submit --master yarn --name arrow-spark /user/local/spark/app/spark.py. Error code is: 1.; 151)
[2024-01-22T22:41:10.260+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-22T22:41:10.276+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-22T22:59:38.898+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-12-22T08:00:00+00:00 [queued]>
[2024-01-22T22:59:38.908+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-12-22T08:00:00+00:00 [queued]>
[2024-01-22T22:59:38.908+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2024-01-22T22:59:38.919+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): test> on 2022-12-22 08:00:00+00:00
[2024-01-22T22:59:38.926+0000] {standard_task_runner.py:57} INFO - Started process 331 to run task
[2024-01-22T22:59:38.930+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_sample_dag', 'test', 'scheduled__2022-12-22T08:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpnl4m6s02']
[2024-01-22T22:59:38.933+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask test
[2024-01-22T22:59:39.002+0000] {task_command.py:416} INFO - Running <TaskInstance: first_sample_dag.test scheduled__2022-12-22T08:00:00+00:00 [running]> on host 3b2231e5c840
[2024-01-22T22:59:39.065+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_sample_dag' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2022-12-22T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-22T08:00:00+00:00'
[2024-01-22T22:59:39.074+0000] {spark_submit.py:236} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-01-22T22:59:39.075+0000] {spark_submit.py:366} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=spark://spark:7077 --name arrow-spark /user/local/spark/app/spark.py
[2024-01-22T22:59:40.175+0000] {spark_submit.py:536} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-01-22T22:59:40.177+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-01-22T22:59:40.177+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-01-22T22:59:40.178+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-01-22T22:59:40.178+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-01-22T22:59:40.178+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2024-01-22T22:59:40.178+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2024-01-22T22:59:40.178+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-01-22T22:59:40.178+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-01-22T22:59:40.178+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-01-22T22:59:40.178+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-22T22:59:40.217+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 467, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark:7077 --name arrow-spark /user/local/spark/app/spark.py. Error code is: 1.
[2024-01-22T22:59:40.223+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_sample_dag, task_id=test, execution_date=20221222T080000, start_date=20240122T225938, end_date=20240122T225940
[2024-01-22T22:59:40.238+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task test (Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark:7077 --name arrow-spark /user/local/spark/app/spark.py. Error code is: 1.; 331)
[2024-01-22T22:59:40.271+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-22T22:59:40.293+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
